#! /bin/sh

# The default is the debug build
WORKTREE_PATH="${HOME}/projects/mesa"
MESA_PATH="${WORKTREE_PATH}/main"
#EXTRA_LIBS_PATH="${HOME}/.local/mesa-dev"
LIBDIR_SUFFIX="lib64"
GL_DRIVER_OVERRIDE=

while true; do
    case $1 in
    "-w")
        # This simply specifies a workdir name
        shift
        MESA_PATH="${WORKTREE_PATH}/${1}"
        shift
        ;;
    "--vk-validate")
        export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
        export VK_DEVICE_LAYERS=VK_LAYER_KHRONOS_validation
        shift
        ;;
    "--iris")
        GL_DRIVER_OVERRIDE=iris
        shift
        ;;
    "--i965")
        GL_DRIVER_OVERRIDE=i965
        shift
        ;;
    "--zink")
        GL_DRIVER_OVERRIDE=zink
        shift
        ;;
    *)
        break
        ;;
    esac
done

if [ -n "${EXTRA_LIBS_PATH}" ]; then
    LD_LIBRARY_PATH="${EXTRA_LIBS_PATH}/${LIBDIR_SUFFIX}:${LD_LIBRARY_PATH}"
fi

if [ -n "${MESA_PATH}" ]; then
    MESA_LIB_PATH="${MESA_PATH}/_install/${LIBDIR_SUFFIX}"

    LD_LIBRARY_PATH="${MESA_LIB_PATH}:${LD_LIBRARY_PATH}"
    if [ -z "${MESA_DRIVERS_PATH}" ]; then
        MESA_DRIVERS_PATH="${MESA_LIB_PATH}/dri"
    fi
    export LIBGL_DRIVERS_PATH="${MESA_DRIVERS_PATH}"
    export GBM_DRIVERS_PATH="${MESA_DRIVERS_PATH}"

    if [ -z "$ICD_NAME" ]; then
        GL_VENDOR=`wflinfo -p gbm -a gl | grep 'OpenGL vendor string'`
        GL_VENDOR=`echo "$GL_VENDOR" | sed -e 's/OpenGL vendor string: //'`
        case "$GL_VENDOR" in
        "Intel")
            ICD_NAME="intel_icd.x86_64.json"
            ;;
        "AMD")
            ICD_NAME="radeon_icd.x86_64.json"
            ;;
        "Panfrost")
            ICD_NAME="panfrost_icd.aarch64.json"
            ;;
        "Broadcom")
            ICD_NAME="broadcom_icd.aarch64.json"
            ;;
        *)
            echo "Unknown OpenGL vendor string: $GL_VENDOR"
        esac
    fi

    export VK_ICD_FILENAMES="${MESA_PATH}/_install/share/vulkan/icd.d/${ICD_NAME}"
    #export VK_ICD_FILENAMES="${MESA_PATH}/_install/share/vulkan/icd.d/intel_icd.i686.json"

    if [ -n "${GL_DRIVER_OVERRIDE}" ]; then
        export MESA_LOADER_DRIVER_OVERRIDE="$GL_DRIVER_OVERRIDE"
    fi

    export IRIS_ENABLE_CLOVER=1
    export OCL_ICD_VENDORS="${MESA_PATH}/_install/etc/OpenCL/vendors"
fi

export LD_LIBRARY_PATH

exec "$@"
