#! /bin/bash
# Fedora setup script for Fedora >= 19
#
# This set of scripts sets up a new fedora install to my personal tastes
# including default software installs, shell configuration, etc.
#
# This particular script totally disables core dumps.  This is very useful
# on machines where one expects to run test suites with lots of crashes
# because the time spent processing core dumps can get rather expensive.
#
# There are multiple ways to disable core dumps.  One is to set a couple of
# fields in /etc/systemd/coredump.conf to make coredumpd discard them.
# However, the core dumps are still generated by the kernel and handed to
# systemd-coredump so there's still significant CPU being burned there.
# Another, and the approach taken in this script is to set core_pattern to
# tell the kernel to invoke /bin/false so that it doesn't even bother
# storing the core dump.  This can be done on-the-fly by
#
#     echo "|/bin/false" > /sys/kernel/core_pattern
#
# Or you can instruct sysctl to do it at boot by adding a 50-coredump.conf
# file to /etc/sysctl.d
#
# To be run as root.

cp 50-coredump.conf /etc/sysctl.d/50-coredump.conf

# The new coredump config file has to be added to the initrd
dracut --force --regenerate-all --install /etc/sysctl.d/50-coredump.conf

# Go ahead and tell the system to execute the file now
sysctl -p /etc/sysctl.d/50-coredump.conf
