#! /bin/sh

# The default is the debug build
MESA_PATH="/home/jason/projects/mesa"
EXTRA_LIBS_PATH="/home/jason/.local"
LIBDIR_SUFFIX="_install/lib64"
ICD_FILENAME="intel_icd.x86_64.json"

case $1 in
"--vk-validate")
    export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation
    export VK_DEVICE_LAYERS=VK_LAYER_LUNARG_standard_validation
    shift
    ;;
"--radv")
    ICD_FILENAME="radeon_icd.x86_64.json"
    shift
    ;;
"-m32")
    LIBDIR_SUFFIX="_install/lib"
    shift
    ;;
esac


if [ -n "${LD_LIBRARY_PATH}" ]; then
    LD_LIBRARY_PATH="${EXTRA_LIBS_PATH}/${LIBDIR_SUFFIX}:${LD_LIBRARY_PATH}"
else
    LD_LIBRARY_PATH="${EXTRA_LIBS_PATH}/${LIBDIR_SUFFIX}"
fi

if [ -n "${MESA_PATH}" ]; then
    MESA_LIB_PATH="${MESA_PATH}/${LIBDIR_SUFFIX}"

    LD_LIBRARY_PATH="${MESA_LIB_PATH}:${LD_LIBRARY_PATH}"
    if [ -z "${MESA_DRIVERS_PATH}" ]; then
        MESA_DRIVERS_PATH="${MESA_LIB_PATH}"
    fi
    export LIBGL_DRIVERS_PATH="${MESA_DRIVERS_PATH}/dri"
    export GBM_DRIVERS_PATH="${MESA_DRIVERS_PATH}/dri"
    export VK_ICD_FILENAMES="${HOME}/.local/share/${ICD_FILENAME}"
    export IRIS_ENABLE_CLOVER=1
    export GALLIUM_PIPE_SEARCH_DIR="${MESA_DRIVERS_PATH}/gallium-pipe"
    export OCL_ICD_VENDORS="${MESA_PATH}/_install/etc/OpenCL/vendors"
fi

export LD_LIBRARY_PATH

exec "$@"
